######################################################################
# Automatically generated by qmake (3.0) ?? 3? 9 17:16:44 2015
######################################################################

TEMPLATE = app
TARGET = TianYun
INCLUDEPATH += . include


QT += widgets qml quick

QMAKE_LFLAGS += "-Wl,-rpath='\$\$ORIGIN/libs'"
QMAKE_CXXFLAGS += "-std=c++11"

# Input
HEADERS += system.h
SOURCES += main.cpp \
           system.cc 
RESOURCES += source.qrc
